
Viridian_tree_cons_seqs.tar:
	wget https://figshare.com/ndownloader/files/45969777
	mv 45969777 Viridian_tree_cons_seqs.tar

Viridian_tree_cons_seqs: Viridian_tree_cons_seqs.tar
	tar -xf Viridian_tree_cons_seqs.tar
